### PR TITLE
Touchpad: add tap-and-drag setting

### LINKED ISSUE #184: Tap-and-drag toggle
It would be great if the OS would have a system level (GUI) option to disable double-tap to select while keeping the single tap to click. This is described in this askubuntu posting.

https://askubuntu.com/a/1115136

### PR DESCRIPTION
**Pull request by cassidyjames**
Fixes #184.

- Switch `tap_to_click` switch to check
- Add `tap_and_drag` check
- Bind its sensitivity to the `tap_to_click` check
- Implicit GLib namespacing for binding flags while we're here

### CODE REVIEW

**Comment by cassidyjames** [comment]
This is where I am now. For some reason binding tap-and-drag sensitivity to the tap-to-click setting isn't working but I haven't revisited that; I'll do it now.

Screenshot from 2021-09-07 11-23-34

I don't know how I feel about the layout. I like Tap-to-click being a switch rather than both being checkboxes, but we could do something like this:

> Tapping: :ballot_box_with_check: Tap to click :ballot_box_with_check: Double-tap and move to drag

Thoughts @elementary/ux?

**Comment by danrabbit** [comment]
@cassidyjames hm yeah the switch feels weird. I'm more in favor of the two checkboxes personally

**Review by danrabbit — DISMISSED** [review]
Works as expected. Nice job!

**Review by danrabbit — CHANGES_REQUESTED** [review]
Oh oops I forgot, can you update appdata :)

**Review by danrabbit — APPROVED** [review]
:shipit:

**Pull request merged**
